version: '3.7'

# docker stack deploy -c toolwp.yml wordpress

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:5
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content 
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user1
      WORDPRESS_DB_PASSWORD: Fancypass
      WORDPRESS_DB_NAME: wpdb
    ports:
      - 8181:80
      - 443:443
    networks:
      - back

  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: Fancypass
      MYSQL_RANDOM_ROOT_PASSWORD: Fancypass
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.7.9-1
    restart: always
    ports:
      - 8182:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: Fancypass
    networks:
      - back

networks:
  back:
volumes:
  db_data:
