version: '3.7'

x-default-opts: 
  &default-opts
  logging:
    options:
      max-size: "10m" 

networks:
  ntw_front:
    external: true
  ntw_proxy:
    external: true

configs:
  traefik.toml:
    file: ./configs/traefik.toml

services:

  socat:
    <<: *default-opts
    image: devmtl/socatproxy:1.1
    networks:
      - ntw_front
      - ntw_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.20'
          memory: 8M
        reservations:
          cpus: '0.10'
          memory: 4M
      labels:
        - "traefik.enable=false"

  traefik:
    <<: *default-opts
    image: traefik:1.7.8-alpine
    ports:
    - target: 80
      protocol: tcp
      published: 80
      mode: ingress
    - target: 443
      protocol: tcp
      published: 443
      mode: ingress
    networks:
      - ntw_front
      - ntw_proxy
    volumes:
      - ./configs/acme.json:/acme.json
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
    command: 
      - --docker
      - --docker.swarmmode
      - --docker.domain=traefik
      - --docker.endpoint=tcp://socat:2375
      - --docker.watch
      - --docker.exposedByDefault=false
      - --logLevel=WARN
      - --api
      - --defaultentrypoints=http,https
      - --docker.network=ntw_front
      - --web.metrics.prometheus
      - --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0"
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.33'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 48M
      labels:
        - traefik.enable=true
        - traefik.port=8080
        - traefik.frontend.rule=PathPrefixStrip:/traefik

# https://github.com/pascalandy/docker-stack-this
