version: '3.3'

services:
  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ntw_front
    deploy:
      mode: global

  portainer:
    image: portainer/portainer:1.17.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
    networks:
      - ntw_front
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role==manager]
      restart_policy:
        condition: on-failure
        max_attempts: 5
      resources:
        limits:
          cpus: '0.33'
          memory: 20M
        reservations:
          cpus: '0.05'
          memory: 10M
      labels:
        - "traefik.frontend.rule=PathPrefixStrip:/portainer"
        - "traefik.backend=portainer"
        - "traefik.port=9000"
        - "traefik.weight=10"
        - "traefik.enable=true"
        - "traefik.passHostHeader=true"
        - "traefik.docker.network=ntw_front"
        - "traefik.frontend.entryPoints=http"
        - "traefik.backend.loadbalancer.swarm=true"
        - "traefik.backend.loadbalancer.method=drr"

networks:
  ntw_front:
    external: true

volumes:
  portainer_data:

# potential setup https://github.com/portainer/portainer/issues/461
# Inspired from https://github.com/portainer/portainer-compose/blob/master/docker-stack.yml

# by Pascal Andy | https://pascalandy.com/
# https://github.com/pascalandy/docker-stack-this
